steps:
  - name: mirror.gcr.io/library/golang
    env: ['GO111MODULE=on']
    args: ['go','build','./...']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/maratona-driver', '.']

images: ['gcr.io/$PROJECT_ID/maratona-driver']